language: java
sudo: true
jdk: oraclejdk11

services:
  - docker

# Environment variables :

# Docker auth
# - User: $DOCKER_USERNAME
# - Password: DOCKER_PASSWORD

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  
script:
  - sh ./scripts/build.sh
  
after_success:
  - docker build . -t $DOCKER_USERNAME/sparql
  - docker push $DOCKER_USERNAME/sparql
